apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix
  namespace: solidvessel
  labels:
    app: apisix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisix
  template:
    metadata:
      labels:
        app: apisix
    spec:
      containers:
      - name: apache-apisix
        image: apache/apisix
        env:
        - name: APISIX_STAND_ALONE
          value: "true"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: apisix-conf-volume
          mountPath: /usr/local/apisix/conf
          subPath: apisix.yaml
      volumes:
      - name: apisix-conf-volume
        configMap:
          name: apisix-conf
