apiVersion: v1
kind: Service
metadata:
  name: apisix
  namespace: solidvessel
spec:
  type: NodePort
  selector:
    app: apisix
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 30080