environment: prod
image:
  repository: public.ecr.aws/s9i7g5t1/solidvessel/payment
  tag: "0.1.0"
  pullPolicy: IfNotPresent
db:
  hostname: payment.db.solidvessel.com
  url: jdbc:postgresql://payment.db.solidvessel.com:5432/payment
spring:
  webExposure: health
  liquibase:
    contexts: sql
replicas: 2
