environment: test
image:
  tag: "1.0.0"
db:
  hostname: payment-db.solidvessel.svc.cluster.local
  url: jdbc:postgresql://payment-db:5432/payment
spring:
  webExposure: "*"
  liquibase:
    contexts: sql,data
replicas: 1
