environment: test
db:
  hostname: payment-db-postgresql.solidvessel.svc.cluster.local
  url: jdbc:postgresql://payment-db-postgresql:5432/payment
spring:
  webExposure: "*"
  liquibase:
    contexts: sql,data
replicas: 1