environment: test
db:
  hostname: order-db-postgresql.solidvessel.svc.cluster.local
  url: jdbc:postgresql://order-db-postgresql:5432/order_db
spring:
  webExposure: "*"
  liquibase:
    contexts: sql,data
replicas: 1