environment: test
image:
  repository: public.ecr.aws/s9i7g5t1/solidvessel/order
  tag: "0.1.0"
  pullPolicy: IfNotPresent
db:
  hostname: order-db.solidvessel.svc.cluster.local
  url: jdbc:postgresql://order-db:5432/order_db
spring:
  webExposure: "*"
  liquibase:
    contexts: sql,data
replicas: 1
