{{ if .Values.environment "test" }}
apiVersion: v1
kind: Service
metadata:
  name: payment-db
  namespace: solidvessel
spec:
  type: NodePort
  selector:
    app: payment-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32004
{{ end }}