apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: apisix-secret
  namespace: solidvessel
spec:
  encryptedData:
    CLIENT_SECRET: AgAMrNsQGATW3bPeHjROUdNaiCw6hPqXaps2gUfjdjbWQzKxWCnjasfDxeT7tUUhA9uGx3CBWxmwfBUlCs98RjhT13AhOjuHA7BpyeUAq7VqPN8eWdM8aD7ctps0kDak9EVoHFnhPvUcV+n6tz/wG9D6+WsDStVcP1TmUHV9400d8YKWe6D0udGrMcBcjlqeCcOwB1FCUFVO/ujRM4ittyee6Qo91KceSDsRgd3WXFmyoRR8rz2n9ma9UiY3UmXoOKtXu74n8mGh3xO43rqaWeKeEjMMA79kQmrA8/MstElLZhcj397gFVKHJaXuQdKR1E/bETw81k/H9zOMqUZk7JSpX7iwck5QiMu6EbjjkfIO1zXg2TUHbnxsSUyVhiz/cuiEU697TnFnYMt6goE+skbvkxiI2bJchl05YBL9FRuE5xBi/fJ7M8OVbjXGUe9L+1O37rhY9i4BLgfUtlhVkqkwMR8ssnA/OzrF5aQxdNyPJKVkp2cFyOlfOFyMSeQn35MYstJxL3Qil6JMsehn6svwBtd6WGLB50+quAnEL2m4CIHNMaN1eDc0A5XMDlVSHKI8zk9RDhHmp9LpJ64Gqnycs6PplBue+z+XfG49IFsFcgcI45WPpYeM0GcToDrRT4NMt/JlRvWxXh/uGl8Uo1Zmq+5fKqZ9D5YzA7LPnBJf56b3oP8VSMQAsVb9NqbM/0GOIJQXG0ud5H3qAYpCRI5BkgMA5x8/0P0=
  template:
    metadata:
      creationTimestamp: null
      name: apisix-secret
      namespace: solidvessel
    type: Opaque
