apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-db-secret
  namespace: solidvessel
spec:
  encryptedData:
    db-password: AgBF625cfem2JDYwDWqgzvs5qf4xuPVYcYJ5Q7ZmMqwERojekCqNDLIXp6zK2Ra1HBITiCVZRTlnPJpinlDw9ZvZFwtQO3t/lIroTLcqPeIbd+hi7iYVyWV3D6QXy2Ka8X8/+TWG3zRs0NcacfSdx1wWHc7Na+ZXC8ObUvmTTeJKmV7sAC6LI+0Crx/9jKEi8uxYPIb5lmdND/BGb2JZ34jZVhUF0NiVOJd6EvhVHu46V/eSg0mzVn2GuMyyDoiR/R0ijEYX7EGYkMxLFuNCpoLhLm6siJjvPnZ+P9Dvpdpfs8j04vk9ChlziWG+LcZ8F2bobVyy5rqfk53bV7wWEu58e5rK3tNY9H1X/Z2UUJui/TliQAoUauSfiyRgrFXUWR0NBQi4xTDfr4oV9CtqfSTVKTSrhkIIfwv4THbwX+PwelwRt+CiVNb1Sr1jPJ3TxN3fb0l+QL8YcvWkpW5KU+i80gQirbyDyyCTevOjTOa/vRkLEPRybDGZMRtVJw5D3IV1xaQZkMEBwv9sde2MNMJVJXwY/yQzru5D2RUEipF6TbDn6PcxIowR6yPk0wBlHKnRa1FEBzz/Yy/Nq14nUqi3zJhFXWSUhQFv1TM00m/c3/IVRDNf2suTKT/CMxPKDrMKBCSrQ1BoZCuDwWBT8THgK6gDubSZhFeP3Az3bl66KizOnqjGpy7xgCnXlLSZs4tCXZJX9622i7lpyq29PwAJZLR0GhwGoCU=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-db-secret
      namespace: solidvessel
    type: Opaque
