apiVersion: v1
kind: ConfigMap
metadata:
  name: account-configmap-prod
  namespace: solidvessel
data:
  application-prod.yaml: |
    spring:
      datasource:
        url: jdbc:postgresql://account.db.solidvessel.com:5432/account
        username: nihilus
        password: 5b03574a-fe81-2d65-553a-68e6a3485ea7
      data:
        redis:
          host: redis-master
          port: 6379
          password: nihilus
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: http://keycloak:80/realms/solidvessel/protocol/openid-connect/certs
    order:
      url: http://order:8080/order
    payment:
      url: http://payment:8080/payment
    management:
      endpoints:
        web:
          exposure:
            include: '*'
    keycloak:
      server-url: http://keycloak:80
