plugins {
    alias(libs.plugins.spring.boot) apply false
    alias(libs.plugins.spring.dependency.management) apply false
    alias(libs.plugins.spring.cloud.contract) apply false
    alias(libs.plugins.jib) apply false
    alias(libs.plugins.lombok) apply false
}

group = 'com.solidvessel'

subprojects {
    pluginManager.withPlugin('java') {
        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(21)
            }
        }

        tasks.withType(JavaCompile).configureEach {
            options.release = 21
        }

        tasks.withType(Test).configureEach {
            useJUnitPlatform()
        }
    }

    pluginManager.withPlugin('jacoco') {
        tasks.named('test') {
            finalizedBy(tasks.named('jacocoTestReport'))
        }

        tasks.named('jacocoTestReport') {
            reports {
                xml.required = true
            }
        }

        tasks.named('jacocoTestCoverageVerification') {
            classDirectories.setFrom(classDirectories.files.collect {
                fileTree(dir: it, exclude: coverageExclusions)
            })
            violationRules {
                rule {
                    limit {
                        counter = 'LINE'
                        value = 'COVEREDRATIO'
                        minimum = 0.75
                    }
                }
            }
        }

        tasks.named('check') {
            dependsOn(tasks.named('jacocoTestCoverageVerification'))
        }
    }
}
