package com.solidvessel.payment.product.model;

public enum ProductSubcategory {
    COMPUTERS, MOBILE_PHONES, TABLETS, AUDIO, CAMERAS, TELEVISIONS, GAMING,
    LIVING_ROOM, BEDROOM, OFFICE, DINING, OUTDOOR_FURNITURE,
    MENS_CLOTHING, WOMENS_CLOTHING, KIDS_CLOTHING, SHOES, CLOTHING_ACCESSORIES,
    HAND_TOOLS, POWER_TOOLS, GARDEN_TOOLS, AUTOMOTIVE_TOOLS,
    KITCHEN_APPLIANCES, CLEANING_APPLIANCES, CLIMATE_APPLIANCES,
    GARDEN, HOME_DECOR, SPORTS_EQUIPMENT, FITNESS, OUTDOOR_SPORTS,
    SKINCARE, HAIRCARE, MAKEUP, ACTION_FIGURES, BOARD_GAMES,
    CHILDRENS_BOOKS, FICTION, NON_FICTION, PANTRY, BEVERAGES, FRESH_FOOD,
    CAR_ACCESSORIES, MOTORCYCLE, PET_FOOD, PET_ACCESSORIES
}
