{{ if eq .Values.environment "prod" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.19.0
    helm:
      values: |
        provider:
          name: aws
        domainFilters:
        - solidvessel.com
        serviceAccount:
          create: false
          name: external-dns
  destination:
    server: https://kubernetes.default.svc
    namespace: solidvessel
  syncPolicy:
    automated:
      prune: true
{{ end }}