{{ if eq .Values.environment "prod" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: external-dns
    targetRevision: 8.3.9
    helm:
      values: |
        provider: aws
        domainFilters:
        - solidvessel.com
        serviceAccount:
          create: false
          name: external-dns
  destination:
    server: https://kubernetes.default.svc
    namespace: solidvessel
  syncPolicy:
    automated:
      prune: true
{{ end }}