apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 14.6.6
    helm:
      values: |
        auth:
          username: guest
          existingPasswordSecret: rabbitmq-secret
        persistence:
          enabled: false
        service:
          type: NodePort
          nodePorts:
            amqp: 32101
            manager: 32102
  destination:
    server: https://kubernetes.default.svc
    namespace: solidvessel
  syncPolicy:
    automated:
      prune: true
---
{{ if eq .Values.environment "test" }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: solidvessel
type: Opaque
data:
  rabbitmq-password: cmFiYml0
{{ end }}
---
{{ if eq .Values.environment "prod" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: solidvessel
spec:
  encryptedData:
    rabbitmq-password: AgCWm6BcPT8TeZQy6BGJbALMqAeb5Sgevwg30QfFu4E9PV07sPHbgvv4gg5X0UUq5mHOtuP101HmaPY7m9jNxwxxSg/We2KxUwFJZG00mUp2hxkP3b/M/upGvSAyceR+Gy2TjoNATbbGC9V/lc3v1L800vqQxokbm8S/4xyCZKXzlbWaF+JNEK8gM9xsV4Tt8F24FRInFZRq8DZQQo1GnTNg46T6fxRXOBHne98afl9WSwJpaPRwm83cvmDNSbj+pRY6sAzCk6tF4vh4rivTUevgJzpfjRiPrcPBuH/L7UhTYQobhLC0o5Vyioy+Ffdvzn5BmGdgWflA/er6SBOpL+0s7VpoV+DVLf8i2zqGU/G1WXWzUhiFxiWtTTY5WjRL0/Qwg79GbRJ/5C5RqSuyP3gPEz3VgtBlcvBapWGyJ4CR3nS+/g4yLi3KMMlep/BTuSLDaqy8I+Y/E6ISkX3HPYaDO6loA9vu5Cbb1wjnyoyLRUyM4r9UgFDzClQ2KnQhBZ+8BxmS2KfLigcbMpQoVa+hdxWlhm3lNR7o5S+ZVtu6TDCye5KUP0BD0x5I/AGMd9sAU08lK4uF/oXiwSiaEHtIRy2rUakrH7GgQ5+wvYHnC7hC9IPXdaAHRdQTau30VNl+b0AEp8Js2/C2v/iI06FtWQZRkShRJgP3g3HDgkgxkuR8eGuikqUPnE31YgXpmWOLXMqiTgtgrohW8+oe2l8cvt3gdaOJ9U4=
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: solidvessel
    type: Opaque
{{ end }}