environment: prod
db:
  hostname: inventory.db.solidvessel.com
  url: postgresql://inventory.db.solidvessel.com:5432/inventory
  password: ${DB_PASSWORD}
redis:
  password: ${REDIS_PASSWORD}
rabbitmq:
  password: ${RABBITMQ_PASSWORD}
spring:
  webExposure: health
keycloak:
  clientSecret: ${KEYCLOAK_CLIENT_SECRET}
  password: ${KEYCLOAK_PASSWORD}
