environment: test
db:
  hostname: inventory-db-postgresql.solidvessel.svc.cluster.local
  url: jdbc:postgresql://inventory-db-postgresql:5432/inventory
spring:
  webExposure: "*"
  liquibase:
    contexts: sql,data
replicas: 2