spring:
  datasource:
    url: jdbc:postgresql://inventory-db-postgresql:5432/inventory
  data:
    redis:
      host: redis-master
      port: 6379
  rabbitmq:
    host: rabbitmq
    port: 5672
management:
  endpoints:
    web:
      exposure:
        include: *