spring:
  profiles:
    active: dev
  application:
    name: inventory
  data:
    redis:
      timeout: 30000
  liquibase:
    change-log: classpath:/db/master.yaml
server:
  servlet:
    context-path: /inventory
exchanges:
  payment: payment.topic
  product: product.topic
queues:
  payment:
    saved: payment.saved
routing-keys:
  payment:
    saved: payment.saved
  product:
    available: product.available
    checked: product.checked
keycloak:
  realm: solidvessel
  client-id: solidvessel-auth
  username: solidvessel-admin
