server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:6002/inventory
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
management:
  endpoints:
    web:
      exposure:
        include: *