spring:
  datasource:
    url: jdbc:postgresql://inventory-db:5432/inventory
  data:
    redis:
      host: redis-master
      port: 6379
  rabbitmq:
    host: rabbitmq
    port: 5672
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/solidvessel/protocol/openid-connect/certs
management:
  endpoints:
    web:
      exposure:
        include: '*'
keycloak:
  server-url: http://keycloak:8080
