spring:
  profiles:
    active: dev
  application:
    name: inventory
  datasource:
    username: nihilus
    password: nihilus
  data:
    redis:
      timeout: 30000
  liquibase:
    change-log: classpath:/db/master.yaml
    contexts: sql,data
server:
  servlet:
    context-path: /inventory
exchanges:
  payment: payment.topic
queues:
  product: product.queue
routing-keys:
  payment:
    saved: payment.saved