server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9876/realms/solidvessel/protocol/openid-connect/certs
management:
  endpoints:
    web:
      exposure:
        include: '*'