AWSTemplateFormatVersion: 2010-09-09
Description: Solidvessel Databases
Resources:
  AccountDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: account
      DBInstanceClass: db.t4g.medium
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: "16.2"
      MasterUsername: nihilus
      MasterUserPassword: 5b03574a-fe81-2d65-553a-68e6a3485ea7
  InventoryDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: account
      DBInstanceClass: db.t4g.medium
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: "16.2"
      MasterUsername: nihilus
      MasterUserPassword: 5b03574a-fe81-2d65-553a-68e6a3485ea7
  OrderDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: account
      DBInstanceClass: db.t4g.medium
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: "16.2"
      MasterUsername: nihilus
      MasterUserPassword: 5b03574a-fe81-2d65-553a-68e6a3485ea7
  PaymentDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: account
      DBInstanceClass: db.t4g.medium
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: "16.2"
      MasterUsername: nihilus
      MasterUserPassword: 5b03574a-fe81-2d65-553a-68e6a3485ea7
  KeycloakDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: account
      DBInstanceClass: db.t4g.medium
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: "16.2"
      MasterUsername: nihilus
      MasterUserPassword: 5b03574a-fe81-2d65-553a-68e6a3485ea7
