AWSTemplateFormatVersion: 2010-09-09
Description: Solidvessel Databases
Resources:
  AccountDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: solidvessel-account-db
      DBInstanceClass: db.t4g.medium
      DBSubnetGroupName: !Ref K8SSubnetGroup
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: "16.2"
      DBSnapshotIdentifier: solidvessel-databases-snapshot-accountdb-kmdeh5lrckwz
  InventoryDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: solidvessel-inventory-db
      DBInstanceClass: db.t4g.medium
      DBSubnetGroupName: !Ref K8SSubnetGroup
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: "16.2"
      DBSnapshotIdentifier: solidvessel-databases-snapshot-inventorydb-opf2kfvocqrf
  OrderDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: solidvessel-order-db
      DBInstanceClass: db.t4g.medium
      DBSubnetGroupName: !Ref K8SSubnetGroup
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: "16.2"
      DBSnapshotIdentifier: solidvessel-databases-snapshot-orderdb-usgtmpuqn5fw
  PaymentDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: solidvessel-payment-db
      DBInstanceClass: db.t4g.medium
      DBSubnetGroupName: !Ref K8SSubnetGroup
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: "16.2"
      DBSnapshotIdentifier: solidvessel-databases-snapshot-paymentdb-umpczzspq9f7
  KeycloakDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: solidvessel-keycloak-db
      DBInstanceClass: db.t4g.medium
      DBSubnetGroupName: !Ref K8SSubnetGroup
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: "16.2"
      DBSnapshotIdentifier: solidvessel-databases-snapshot-keycloakdb-xf2sjwcuamhd
  K8SSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: Databases should be in the same VPC with the K8S cluster
      SubnetIds:
      - <subnet-1>
      - <subnet-2>
      - <subnet-3>
