AWSTemplateFormatVersion: 2010-09-09
Description: Solidvessel Databases
Resources:
  AccountDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: account
      DBInstanceClass: db.t4g.medium
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: "16.2"
      MasterUsername: nihilus
      MasterUserPassword: nihilus
  InventoryDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: account
      DBInstanceClass: db.t4g.medium
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: "16.2"
      MasterUsername: nihilus
      MasterUserPassword: nihilus
  OrderDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: account
      DBInstanceClass: db.t4g.medium
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: "16.2"
      MasterUsername: nihilus
      MasterUserPassword: nihilus
  PaymentDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: account
      DBInstanceClass: db.t4g.medium
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: "16.2"
      MasterUsername: nihilus
      MasterUserPassword: nihilus
  KeycloakDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: account
      DBInstanceClass: db.t4g.medium
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: "16.2"
      MasterUsername: nihilus
      MasterUserPassword: nihilus
