{{ if eq .Values.environment "test" }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: solidvessel
type: Opaque
data:
  KC_DB_USERNAME: bmloaWx1cw==
  KC_DB_PASSWORD: bmloaWx1cw==
{{ end }}
---
{{ if eq .Values.environment "prod" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-db-secret
  namespace: solidvessel
spec:
  encryptedData:
    KC_DB_PASSWORD: AgB7ptq4mlpeshi+g1uDGy5Z5hIhg+ttxZgFDAltK+t6n2RmIOLBu1lH1eIbUQO8pcnA6Y2UXqTld5zSxf8a5f4R63I7ciHRsAsVrXg+XRcJe7cuHuivDT/xhj82b6h438JJxBjZJtx1hI831hCMNVMSHcfBv7TpoRAfVDXlTaPrctv5uc/LGpZvr2D4BHcv7avdeY5n94vP7SxzgewTjst808SD/ohMO3fZ6KFyk4cMTBSV2sL223vZ3J1In5MOMgDvtxYF5KFfKCaM64vwrJMaBqNW6kVeOTR+cpDfQC90aglhPkrCb2et+u4jj0uvtSxIlpOtgcF/VzJx+/NdH8SNYtUQLj+f4L0+M1vPqKUMifagki2XBK4sao59lIhcoqLYQH42grchYFElJO4XFWQAhjBx1areUyXUa0pD+l0aphf3/fqHLfmLuNt7cdmVFq9gmQNmd7B+dVrzjDP1PJEqeYRaEcKBfaZEk1LSWEdrzfUdzBKjYkOiNrnw9LFLH/dHISzBqiziPGXdFZro0KwRdxYAx6o/hKy9dU9sfYwB799iKqzYa347/WusMfzLFIVOXNaYHE7uCcdIeiRw+ECtwsk/kit3wMLMoIW/86hlj6EDrBc2PW2tIOhfR8ykICuJAgi8NIK+0Eca2tfWNd8QG7LWK0/MzbgySBKWTJcAFwDwCPEKbeyQx3v0feI6cGuvjLSIHpvqi9Phrp51Sed1409sFImudbU=
    KC_DB_USERNAME: AgCBpIsB+b43o/LsNGAPnHUAfRmdIqhqw4ZMV7uvDXaKj3QUYGDuA6ozNYC/Qjh0ErLYjq/LbCK5mzkcNNF6S2tifJPZMcskJ2cs2CDrevRiLmhduvwcKpboBtV/ytbZzC446MHqXmwMsYyaCulhbYvgalzefuNOuwRfy9XtEm9qscbCwKeHQ0FezFatu3UPvYYHQspH0+hh6Cv/92jfx0HGGUpDxMekwSzXQcobTg6N1m6O316YwmPeIp/Ce3317Jh42RxdXQ0/Xz9c03Ioi3I57bjbRxP/HnS96RgUzZiOTqqF93126k5WGEimem41dyKoXuZ6kK0gSnDCvAaG2vOB+z1DwU03z4yBFC7bYkJKOdHAL/Zfh3XNG6T6lIvlnO22c/mgz3duCCtgbvTieEzROuLcXqd1cgVev4PM0bhNGpdxr4IEcNDem/yVLWq9EPUBPoGw0ihPLKiZln6sJE01cRMJ8bRpmpHHLG+cqjyzxTQ6RvhuGfokbREeTRZcGTiAmJBJeBY9n1/+VEXPwlb+5eppnLVw+IOcbbvaqJpMX+tx0QqVL3LnsXHPQSbtj/o9VyWMdltIx+JKhKFDW/+iIyF7hQLSE3GA+bG79GhjFFu0dlylpibi7nWV0xjzzEiApCCMjRpcIsW/uNmHiY8PtrlRmxiweloiuKo0XM1qvLJ2P0deIbCo07Fu2d79B6oYxORGPJEQ
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-db-secret
      namespace: solidvessel
    type: Opaque
{{ end }}