{{ if eq .Values.environment "test" }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: solidvessel
type: Opaque
data:
  admin-password: c3ZhZG1pbg==
{{ end }}
---
{{ if eq .Values.environment "prod" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin-secret
  namespace: solidvessel
spec:
  encryptedData:
    admin-password: AgAL9LM8saZg4izInPscHuIXTCZHYIe3TGXjuG8s/RF6qRyurtqMVKN0t1HjS7U+EVTN3CG1YWml+u6bCUcMiuZtg/pIbl2TlNUL9cSegOgO4Xxxrr43TpHeYRkwPclqSs50IZNFtXn5vTtTLYg/QthhRvX92ahJB6+cu6183nsTa9ZW01lABT2Z7Bl5OrA/Zh09QdVrtdV/a3iI0kTwb+7w76yFyus1FXdPTzf2MTwLLD4tb5O9DejxYRb0vnkC/vUV4nYQIn/2ey7IwR1BzGSCKKKTVJUWU5w6MBlcv4AjxUppsLfz8RdsV84g2jVZmpNIz0yqQ7UiEJHycLb/D6VDhoZDotMTs+PgIKpaTDq2W/7Q0xESI0vltuuaSdq5TwFCpTcE/iZ5WK9tcvuSTaZTevZGUZk8m6VXCTfPDTuW4n+2sZ3jKqbEqZXsdh47uRnEYJs1g3xcrFx/9U6wpIlyhfBHSM1VacTm/lcEqaomtPhqOeVhyU2cHxfIPv3ilGc09v+W6QVf5cE18lG99nxRUcKbWU1E8XGrJtt2pODDorfv8qiG435OuWJ8u5rYJx3Pc3qQTdslmYwLaCHPUHgGZ683HPdbo674w6Zf2iwH2swdTTzIQZgAwILVkclrVN9LB7uemV2nkM52vqApSVzdnIw7QH1Yl3YW79cArs29O2cnRDBVl7aT2tApMzka74+P3n10WWI02PwEeyyQk/zhv6NcO4NHnh4=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin-secret
      namespace: solidvessel
    type: Opaque
{{ end }}