{{ if eq .Values.environment "test" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.27
    helm:
      values: |
        global:
          postgresql:
            auth:
              database: keycloak
              username: nihilus
              existingSecret: keycloak-db-secret
        primary:
          persistence:
            enabled: false
          service:
            type: NodePort
            nodePorts:
              postgresql: 32000
  destination:
    server: https://kubernetes.default.svc
    namespace: solidvessel
  syncPolicy:
    automated:
      prune: true
{{ end }}