{{ if eq .Values.environment "test" }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: solidvessel
type: Opaque
data:
  KC_BOOTSTRAP_ADMIN_USERNAME: YWRtaW4=
  KC_BOOTSTRAP_ADMIN_PASSWORD: c3ZhZG1pbg==
{{ end }}
---
{{ if eq .Values.environment "prod" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin-secret
  namespace: solidvessel
spec:
  encryptedData:
    KC_BOOTSTRAP_ADMIN_PASSWORD: AgBNAo+vtUrtlMqchQsPwF1q/Giol37P6HF4mzPIn5pd7VWTVguOFLkv3mm3pMQ7CbYqTn5tfYifCUOgZEbB0wG7gMGYgqNyOIcAPO6QngGqaisZ5AJP2EGaI40YlRnyMxXt8CgTBqLRlmWqxqjCyFhBYDsxop0n2hRxfuriCK9YqMCcU4pgieVb51UYamyj3qIvjWI+6t29uDCaqFYwC+DWIFTgqCmDR2Gi1bzKBjjfum29GNwmJWPBCeMMgQ3wVqTxNFK20Ne1mW1dRJSFlnTyLCE92hQstrqpb7oP77Q6EPTn7cWrW8b0BXhq4eIwF5WeyeLHYtiTpnnimw2JkIXS7zaJAiIpIw67jN2B22O7P2qfp3DURD3zBKSAJrBOWGrjA69usRpSzVmTnAs+4OwboeAkjX/0cXXw5RvHQlkKfGG19SEERa0BZ2RuX8N5Hy8zfGqKHYDZ8P8YOv84GMUdz9gnXMrcRfOJGwmFuQFqyDeU73nXfqMR/S+Fscm1UGbIwT7ublBodFfbyybkiCJvtKp9SXWOoftvMUWAS0fcHxTcoqy6wlSi25X4Nh0c8qArw8qc311xH1ZWnNGGhNaiA8uIYjPEJ/dumqZEHBE81LqQ6tbN0TKdKgT+ELxYzya9Fu5GtKFPqE5HcyGRr36Gx6rmuOSHe1/DT/lA+TAH+VhT99YIFvWNMvec/ExkMmwmU5popr6ufu3MNX/Ni5JuMmnzfMOXqMg=
    KC_BOOTSTRAP_ADMIN_USERNAME: AgAiYRmxIEj7OxAcRqpV53hl+lEw5CfTaTUPLYtb31jxyTbnh7oaiZw7UyOiqMX1PbBlnFzSY6TTajCLsvelsUpMR/HeCQPglijkBwNjClz7EutUFDJ5weVEILK6C1YEYJqWJwXOC4SXcpQ6NPCPHyR1WjO0XbvQGivMdC1jX9qGmbQAnl7YWhZuYIaLpTNSR8AnaPNxcNQGNDBPQ6jRgjzDWK/FyccMbkhN4rzKonWOAAxpmJqr9ytn4+kWGkSVZ46MLjVOKc9ZgsfqoSX1O3y/JZCR3f7Qw1885cpTcw7sT586YK9O4CEk4jrwRfA2D8manxycmNomXrUH4rU98Ktiq1B+Zq3q8v8VfBJTcaL8hI/LIOyYAnyQU5p/VxOZFBG+yCc4GZj9nJNqyqynqMgXzXaibamSeklrD6qgX/EhmKzwpGuOKoTlYVtkRQCeJumdX0N4ABdGVnny4yUz73ld17Sg65yz6bBdX2w6V3vqEEJJqeVf6USkBaf+AAUnE2rtaL5YIw9Le706FpFoQysSU8ZIJM8a5DgejJk4rgygz2fWhMnqZUVotSmJqnoPptB7m7PmEsHs1+R9Td877x+7Ers2JEUqxXFTBpdL02SPkWZpUrccmubZvOEhZSF1FfCZYYWDJMXxX/8cQa05W6HOqaox2qgVa9GhhvOsNpUzp+WWlzYe63fQVIGYJPJv9mNLI5XDtA==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin-secret
      namespace: solidvessel
    type: Opaque
{{ end }}