{{ if eq .Values.environment "test" }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: solidvessel
type: Opaque
data:
  password: bmloaWx1cw==
  postgres-password: bmloaWx1cw==
  db-password: bmloaWx1cw==
{{ end }}
---
{{ if eq .Values.environment "prod" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-db-secret
  namespace: solidvessel
spec:
  encryptedData:
    db-password: AgAuU5OBrlH1KD+E6Jg47CnwVMvUJZnizqV40FIOo4HXQIdV6V8CMa+pM8Wwniggan8WFjHu2Gu9jrHiH0XY1ZEM5igrZm7Bh8H94oCB3CDzx8s+xuxWK5Hf7qo69AL+8+iISh0VgurLEbUsxbNwvgv7UL4agvy2+6KEgeWcffTuWdBjcaqtwIQ2AtQRBaFOIl0gQKRArfZjdN4gea40CaNG0HR1PZm/+Mly179tgCtiIi75HIDkvjlV1/RaSNrBKDKNx9vtoZPLi6BQcwQ3t/9Yg4CoR8wGvj8AfHjb7AN+WWCo3aysrvX+UX5Fty5jFyGIs/gI+GukKcGGPRuKJOR50mOkIqv3zHY4yAJ6eKmS5NirB8DvuMvq+w6U/dBbXMhnJTpHCKfG80RJJJh0Y/f6WKV8Z+jOmaanfBVR1nCyWV1TtARp4EECB/VGXaat08octEVkCveVy8CmBjQFQD9l2vkXFqss5k9foUu2MFCnBZWri25ByH7PFNCZLo3B2xAslBKCdY1+pKJTMyeNVg/KXCfx58jm3MLIsMlAUuhjaTCtxYLjmWt2FnHD4ECX8tUwLvpIAhUWi2rThTyRd87AFqa4hUfJjDx8IfakJ45TASEb4fQzGCFjkTN6LFNE3B5QBDxgvpXyU/B+CIX0lDakQXZLcSNEtMofJsbJ06SBZCUVdJNK4Rrw7YT3ASRWVwaNu7c5VtbgGRrVaBsrsLDgYje/sFTTgL0=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-db-secret
      namespace: solidvessel
    type: Opaque
{{ end }}