apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://registry-1.docker.io/cloudpirates/keycloak
    chart: keycloak
    targetRevision: 0.4.0
    helm:
      values: |
        production: true
        service:
          type: NodePort
          ports:
            http: 8080
        keycloak:
          existingSecret: keycloak-admin-secret
        postgres:
          enabled: false
          auth:
            host: {{ .Values.db.hostname }}
            database: keycloak
            username: nihilus
            password: temp-password
        extraEnv:
          KEYCLOAK_HOSTNAME: http://keycloak:8080
          KC_HTTP_ENABLED: "true"
          KC_PROXY_HEADERS: forwarded
        {{ if eq .Values.environment "test" }}
        extraVolumes:
        - name: keycloak-realm-volume
          configMap:
            name: keycloak-realm
        - name: keycloak-users-volume
          configMap:
            name: keycloak-users
        extraVolumeMounts:
        - name: keycloak-realm-volume
          mountPath: /opt/bitnami/keycloak/data/import/solidvessel-realm.json
          subPath: solidvessel-realm.json
        - name: keycloak-users-volume
          mountPath: /opt/bitnami/keycloak/data/import/solidvessel-users-0.json
          subPath: solidvessel-users-0.json
        extraStartupArgs: "--import-realm"
        {{ end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: solidvessel
  syncPolicy:
    automated:
      prune: true
