apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: solidvessel
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.3
        ports:
        - containerPort: 8080
        env:
        - name: KC_HOSTNAME
          value: http://keycloak:8080
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_PROXY_HEADERS
          value: forwarded
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL
          value: jdbc:postgresql://{{ .Values.db.hostname }}:5432/keycloak
        - name: KC_FEATURES
          value: hostname
        envFrom:
        - secretRef:
            name: keycloak-admin-secret
        - secretRef:
            name: keycloak-db-secret
        volumeMounts:
        - name: keycloak-realm-volume
          mountPath: /opt/keycloak/data/import/solidvessel-realm.json
          subPath: solidvessel-realm.json
        - name: keycloak-users-volume
          mountPath: /opt/keycloak/data/import/solidvessel-users-0.json
          subPath: solidvessel-users-0.json
        args:
        - "start"
        - "--import-realm"
      volumes:
      - name: keycloak-realm-volume
        configMap:
          name: keycloak-realm
      - name: keycloak-users-volume
        configMap:
          name: keycloak-users