apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: solidvessel
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: [ 'sh', '-c', "until nslookup paymentdb.solidvessel.com; do echo waiting for database; sleep 1; done" ]
      - name: wait-for-keycloak
        image: busybox
        command: [ 'sh', '-c', "until nslookup keycloak.solidvessel.svc.cluster.local; do echo waiting for keycloak; sleep 1; done" ]
      containers:
      - name: payment-app
        args: [ "--spring.profiles.active=prod" ]