apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: solidvessel
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: [ 'sh', '-c', "until nslookup payment.db.solidvessel.com; do echo waiting for database; sleep 1; done" ]
      - name: wait-for-keycloak
        image: busybox
        command: [ 'sh', '-c', "until nslookup keycloak.solidvessel.svc.cluster.local; do echo waiting for keycloak; sleep 1; done" ]
      containers:
      - name: payment-app
        args:
        - "--spring.profiles.active=prod"
        - "--spring.datasource.url=jdbc:postgresql://payment.db.solidvessel.com:5432/payment"
        - "--spring.datasource.username=nihilus"
        - "--spring.datasource.password=${DB_PASSWORD}"
        - "--spring.data.redis.host=redis-master"
        - "--spring.data.redis.port=6379"
        - "--spring.data.redis.password=${REDIS_PASSWORD}"
        - "--spring.rabbitmq.host=rabbitmq"
        - "--spring.rabbitmq.port=5672"
        - "--spring.rabbitmq.password=${RABBITMQ_PASSWORD}"
        - "--spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:80/realms/solidvessel/protocol/openid-connect/certs"
        - "--management.endpoints.web.exposure.include=*"
        - "--keycloak.server-url=http://keycloak:80"
        - "--keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}"
        - "--keycloak.password=${KEYCLOAK_PASSWORD}"
        envFrom:
        - secretRef:
            name: payment-secret