apiVersion: v1
kind: Service
metadata:
  name: inventory-db
  namespace: solidvessel
  labels:
    app: inventory-db
spec:
  selector:
    app: inventory-db
  ports:
  - name: inventory-db
    port: 5432
    targetPort: 5432
    nodePort: 32002
  type: NodePort