{{ if eq .Values.environment "test" }}
apiVersion: v1
kind: Secret
metadata:
  name: apisix-secret
  namespace: solidvessel
type: Opaque
data:
  CLIENT_SECRET: R0pEQ3k0QzdMU2VGbWdnYVJ0WnV0U0haSEJhVENhdkU=
{{ end }}
---
{{ if eq .Values.environment "prod" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: apisix-secret
  namespace: solidvessel
spec:
  encryptedData:
    CLIENT_SECRET: AgA4Jt17jLaHjc9SiDji8dCALiqPiYNbebTyd0khQyHVyYvG7TsaK3c6sO/jLgQgUmc8OTwO/v+315mtFRjom98c/XFoCJ2P9TWayPZuxybTx/2zowKNaQBN2mGAxDPB1gSJsWvnKcHuEliZ2lK/DL9JoBwr55u7mYXMcG0jxXGDfS8osBl2xTgWFNWIHzQcpSy4glDlyT+0Vr2XRd5zYhRnOkUPjdUfFyHy64szBjx4OoVHN+4joO0Ns5AW3C1hwbF+OLomDzHG1FZBuz+TtaLawgGZWvtPMhAUBhyZLM+EHBqB2Jpcd9UXhgJ5wc2HiJO/HaZ7tFkVZgTvKjzIuk6GM2uTEiD7uuITb2+a4Rcn9avksh0osoCJrFc1oM1f4ZrMI7iZpdmHCUfQ15CctlQ11LfYMYGbiSd4Dn0AF6TrUGj34VINba3POIBsgyJSz4kfRRN97g15MW1Tai+qthyhWn+PvbLtz1zDD5GPFE4yomCNrkfSEEoCaHVNftnnTMsN4UkzATJm1JjZ/KFq4pkjD1iLruinf32+gi898Ayoom+ghCvltOTJKx3xflfUjwDDho6lvs/R3W3OjItdurCMBTbLb2s6kxC7txec0yTxOhCXlh75LuI57SiG+o2+NTMUDmb3V9H6YW6yXk2Bs/MbGgkHQ7nUctzRLuWJHkHEAn+OxbkRCS3dKLu9sPYnyXUuVWk2B8ia0uZX0Mhy8dGrmNdq7CzbMIRqJaJX49J6ZA==
  template:
    metadata:
      creationTimestamp: null
      name: apisix-secret
      namespace: solidvessel
    type: Opaque
{{ end }}