apiVersion: v1
kind: Service
metadata:
  name: apisix
  namespace: solidvessel
  labels:
    app: apisix
spec:
  selector:
    app: apisix
  ports:
  - name: apisix
    port: 8080
    targetPort: 9080
    nodePort: 30080
  type: NodePort