apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-conf
  namespace: solidvessel
data:
  apisix.yaml: |
    routes:
    - id: token
      uri: /realms/solidvessel/protocol/openid-connect/token
      upstream:
        nodes:
          "keycloak:8080": 1
        type: roundrobin
    - id: auth
      uri: /auth/*
      upstream:
        nodes:
          "localhost:80": 1
        type: roundrobin
      plugin_config_id: 1
    - id: account
      uri: /account/*
      upstream:
        nodes:
          "account:8080": 1
        type: roundrobin
      plugin_config_id: 1
    - id: inventory
      uri: /inventory/*
      upstream:
        nodes:
          "inventory:8080": 1
        type: roundrobin
      plugin_config_id: 1
    - id: order
      uri: /order/*
      upstream:
        nodes:
          "order:8080": 1
        type: roundrobin
      plugin_config_id: 1
    - id: payment
      uri: /payment/*
      upstream:
        nodes:
          "payment:8080": 1
        type: roundrobin
      plugin_config_id: 1
    plugin_configs:
    - id: 1
      plugins:
        openid-connect:
          client_id: "solidvessel-auth"
          client_secret: ${{"{{CLIENT_SECRET}}"}}
          discovery: "http://keycloak:8080/realms/solidvessel/.well-known/openid-configuration"
          scope: "openid profile"
          bearer_only: true
          realm: "solidvessel"
          redirect_uri: {{ .Values.redirectUri }}
          logout_path: "/auth/logout"
          access_token_in_authorization_header: true
          set_id_token_header: false
          set_userinfo_header: false
        proxy-rewrite:
          headers:
            remove:
            - "sec-fetch-site"
            - "sec-fetch-mode"
            - "sec-fetch-user"
            - "sec-fetch-dest"
            - "sec-ch-ua"
            - "sec-ch-ua-mobile"
            - "sec-ch-ua-platform"
            - "accept-language"
            - "upgrade-insecure-requests"
            - "cookie"
      desc: "oidc"
    #END