{{ if .Values.environment "test" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-conf
  namespace: solidvessel
data:
  apisix.yaml: |
    routes:
    - id: auth
      uri: /auth/*
      upstream:
        nodes:
          "localhost:80": 1
        type: roundrobin
      plugin_config_id: 1
    - id: account
      uri: /account/*
      upstream:
        nodes:
          "localhost:31001": 1
        type: roundrobin
      plugin_config_id: 1
    - id: inventory
      uri: /inventory/*
      upstream:
        nodes:
          "localhost:31002": 1
        type: roundrobin
      plugin_config_id: 1
    - id: order
      uri: /order/*
      upstream:
        nodes:
          "localhost:31003": 1
        type: roundrobin
      plugin_config_id: 1
    - id: payment
      uri: /payment/*
      upstream:
        nodes:
          "localhost:31004": 1
        type: roundrobin
      plugin_config_id: 1
    plugin_configs:
    - id: 1
      plugins:
        openid-connect:
          client_id: "solidvessel-auth"
          client_secret: "GJDCy4C7LSeFmggaRtZutSHZHBaTCavE"
          discovery: "http://localhost:31080/realms/solidvessel/.well-known/openid-configuration"
          scope: "openid profile"
          bearer_only: true
          realm: "solidvessel"
          redirect_uri: "http://localhost:9080/auth/callback"
          logout_path: "/auth/logout"
          access_token_in_authorization_header: true
          set_id_token_header: false
          set_userinfo_header: false
        proxy-rewrite:
          headers:
            remove:
            - "sec-fetch-site"
            - "sec-fetch-mode"
            - "sec-fetch-user"
            - "sec-fetch-dest"
            - "sec-ch-ua"
            - "sec-ch-ua-mobile"
            - "sec-ch-ua-platform"
            - "accept-language"
            - "upgrade-insecure-requests"
            - "cookie"
      desc: "oidc"
    #END
{{ end }}