apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: apisix
    targetRevision: 6.0.0
    helm:
      values: |
        controlPlane:
          enabled: false
          pdb:
            create: false
          tls:
            enabled: false
          dashboardEnabled: false
        ingressController:
          enabled: false
          pdb:
            create: false
        etcd:
          enabled: false
        dataPlane:
          service:
            type: NodePort
            ports:
              http: 8080
              metrics: 8081
            nodePorts:
              http: "30080"
          containerPorts:
            http: 8080
          extraConfig:
            deployment:
              role: data_plane
              role_data_plane:
                config_provider: yaml
          extraEnvVarsSecret: apisix-secret
          lifecycleHooks:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "apisix reload"]
          extraVolumes:
          - name: routes
            configMap:
              name: apisix-conf
          extraVolumeMounts:
          - name: routes
            mountPath: /usr/local/apisix/conf/apisix.yaml
            subPath: apisix.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: solidvessel
  syncPolicy:
    automated:
      prune: true