apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: solidvessel
spec:
  template:
    spec:
      containers:
      - name: order-app
        args: [ "--spring.profiles.active=prod" ]