apiVersion: v1
kind: Service
metadata:
  name: payment-db
  namespace: solidvessel
  labels:
    app: payment-db
spec:
  selector:
    app: payment-db
  ports:
  - name: payment-db
    port: 5432
    targetPort: 5432
    nodePort: 32004
  type: NodePort