apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: solidvessel
  labels:
    app: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: [ 'sh', '-c', "until nslookup payment-db.solidvessel.svc.cluster.local; do echo waiting for database; sleep 1; done" ]
      - name: wait-for-keycloak
        image: busybox
        command: [ 'sh', '-c', "until nslookup keycloak.solidvessel.svc.cluster.local; do echo waiting for keycloak; sleep 1; done" ]
      containers:
      - name: payment-app
        image: ahmsay/solidvessel-payment
        imagePullPolicy: Always
        args:
        - "--spring.profiles.active=test"
        - "--spring.datasource.url=jdbc:postgresql://payment-db:5432/payment"
        - "--spring.datasource.username=nihilus"
        - "--spring.datasource.password=nihilus"
        - "--spring.data.redis.host=redis-master"
        - "--spring.data.redis.port=6379"
        - "--spring.rabbitmq.host=rabbitmq"
        - "--spring.rabbitmq.port=5672"
        - "--spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/solidvessel/protocol/openid-connect/certs"
        - "--management.endpoints.web.exposure.include=*"
        - "--keycloak.server-url=http://keycloak:8080"
        - "--keycloak.client-secret=GJDCy4C7LSeFmggaRtZutSHZHBaTCavE"
        - "--keycloak.password=svadmin"
        ports:
        - containerPort: 8080