apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: solidvessel
  labels:
    app: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: [ 'sh', '-c', "until nslookup payment-db-postgresql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for database; sleep 1; done" ]
      - name: wait-for-keycloak
        image: busybox
        command: [ 'sh', '-c', "until nslookup keycloak.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for keycloak; sleep 1; done" ]
      containers:
      - name: payment-app
        image: ahmsay/solidvessel-payment
        imagePullPolicy: Always
        args: [ "--spring.profiles.active=test" ]
        ports:
        - containerPort: 8080