{{ if eq .Values.environment "test" }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: solidvessel
type: Opaque
data:
  REDIS_PASSWORD: cmVkaXM=
{{ end }}
---
{{ if eq .Values.environment "prod" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: solidvessel
spec:
  encryptedData:
    REDIS_PASSWORD: AgB30FxoSJB+qXaukq98UYjveuKunSDuNz48+fsfUKmgEeKgGX1hjxNm7m/ajkUd/lv8lSNVgfQXE6tpE2OMm4tkdRhQnXaAbOCZECxCXZ/Nah7d3Re4hnSTsQq7ZT6bF5yEzAtpcs/+t1lGTvGyKUlrpDb71SsXBMw13v2tGCqSY76qHW5jrY2alhfNYvHGu+jsUIKjZXjxY/PVawSqYQ9FFu7y2H8ADoKE+nfRPKHksoUmWug6lxHCgNeX5g/ExjZVUR6uRxIDsjZEe0PPFZT2CIBLiWxyGDamMon2IHqWMwnJJSCd4HlnSyH05cZuPP0zuHQgji0fjjAhzIp/JZJBXfx5R1mTiYWrngzoGJg2PyoEgLis7lU1Qrv3CeZW7J1SLxOmmDWT3VfE05Yb2amvaeTMg+KTNPOHgsj/wkACdAibhia6aRg6xejJS/6AGAdWbVfvNiiGoYKCuUqoLsemaEoYCRplBKMzKcw7esTVedk0EdQryH9GoxTy1Wu9Ldix9bh/ZAqdeYrQUOEHIzY1Kc1l/zljSL/qTXg0KBWWUvBymgZer2ed/3gIp7U0aiPE4uMF3BYcnTWNqG7seI63cCmePlwQ6UYMjL6SiU9lG+52hnJiB/qYEDI9cp/VlDL6PTYPfAv5IclCEO0EZZVwC5q5t+7D0eQ+UZ2ss8k2mvYylIswoyVGYrJMk4bjLJ3qWz0TjQ==
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: solidvessel
    type: Opaque
{{ end }}
