apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: solidvessel
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  type: ClusterIP