{{ if eq .Values.environment "test" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: account-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.27
    helm:
      values: |
        global:
          postgresql:
            auth:
              database: account
              username: nihilus
              existingSecret: account-db-secret
        primary:
          persistence:
            enabled: false
          service:
            type: NodePort
            nodePorts:
              postgresql: 32001
  destination:
    server: https://kubernetes.default.svc
    namespace: solidvessel
  syncPolicy:
    automated:
      prune: true
---
apiVersion: v1
kind: Secret
metadata:
  name: account-db-secret
  namespace: solidvessel
type: Opaque
data:
  password: bmloaWx1cw==
  postgres-password: bmloaWx1cw==
{{ end }}