apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: solidvessel
  region: eu-central-1
  version: "1.30"
availabilityZones:
- eu-central-1a
- eu-central-1b
- eu-central-1c
managedNodeGroups:
- name: ng-1
  privateNetworking: true
  instanceType: t3.large
  amiFamily: Bottlerocket
  minSize: 2
  maxSize: 5
  desiredCapacity: 3
  volumeSize: 20
vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    attachPolicyARNs:
    - "arn:aws:iam::<aws_account_id>:policy/AWSLoadBalancerControllerIAMPolicy"
  - metadata:
      name: external-dns
      namespace: solidvessel
    attachPolicyARNs:
    - "arn:aws:iam::<aws_account_id>:policy/AllowExternalDNSUpdates"
addons:
- name: vpc-cni
  version: latest
  attachPolicyARNs:
  - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
  version: latest
- name: kube-proxy
  version: latest
