version: 0.2
env:
  shell: bash
phases:
  pre_build:
    commands:
    - pip install bcrypt
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  build:
    commands:
    - aws eks update-kubeconfig --region $AWS_REGION --name solidvessel
    - kubectl create namespace argocd
    - kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    - kubectl -n argocd patch deploy argocd-server --type=json -p='[{ "op":"add", "path":"/spec/template/spec/containers/0/args/-", "value":"--insecure" }]'
    - kubectl -n argocd patch secret argocd-secret -p '{"stringData":{"admin.password":"'$(python3 -c "import bcrypt; print(bcrypt.hashpw(b'$ARGOCD_PASSWORD', bcrypt.gensalt()).decode())")'","admin.passwordMtime":"'$(date +%FT%T%Z)'"}}'
    - sleep 60
    - kubectl create ns sealed-secrets
    - aws secretsmanager get-secret-value --secret-id solidvessel-custom-tls --query SecretString --output text | kubectl apply -f -
    - kubectl create -f .kubernetes/SealedSecrets.yaml
    - sleep 10
    - perl -i -pe"s/values-test/values-prod/" .kubernetes/Root.yaml
    - kubectl create -f .kubernetes/Root.yaml
#    - load_balancer_arn=None
#    - until [[ $load_balancer_arn != 'None' ]]; do echo 'Waiting for load balancer to be generated...'; sleep 10; export load_balancer_arn=$(aws resourcegroupstaggingapi get-resources --tag-filters Key=ingress.k8s.aws/resource,Values=LoadBalancer Key=ingress.k8s.aws/stack,Values=common-ingress-group --tags-per-page 100 --query "ResourceTagMappingList[0].ResourceARN" --output text); done
#    - LOAD_BALANCER_DNS_NAME=dualstack.$(aws elbv2 describe-load-balancers --load-balancer-arns $load_balancer_arn --query "LoadBalancers[0].DNSName" --output text)
#    - LOAD_BALANCER_HOSTED_ZONE_ID=$(aws elbv2 describe-load-balancers --load-balancer-arns $load_balancer_arn --query "LoadBalancers[0].CanonicalHostedZoneId" --output text)
#    - aws cloudformation deploy --template-file .ci/production/dns-records.yaml --stack-name solidvessel-dns-records --parameter-overrides LBDNSName=$LOAD_BALANCER_DNS_NAME LBHostedZoneId=$LOAD_BALANCER_HOSTED_ZONE_ID
