apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: 17.3.6
    helm:
      values: |
        production: true
        proxy: edge
        auth:
          adminUser: admin
          adminPassword: admin
        postgresql:
          enabled: false
        externalDatabase:
          host: keycloakdb.solidvessel.com
          database: keycloak
          user: nihilus
          password: 5b03574a-fe81-2d65-553a-68e6a3485ea7
        extraVolumes:
        - name: keycloak-realm-volume
          configMap:
            name: keycloak-realm
        - name: keycloak-users-volume
          configMap:
            name: keycloak-users
        extraVolumeMounts:
        - name: keycloak-realm-volume
          mountPath: /opt/bitnami/keycloak/data/import/solidvessel-realm.json
          subPath: solidvessel-realm.json
        - name: keycloak-users-volume
          mountPath: /opt/bitnami/keycloak/data/import/solidvessel-users-0.json
          subPath: solidvessel-users-0.json
        extraStartupArgs: "--import-realm"
  destination:
    server: https://kubernetes.default.svc
    namespace: solidvessel
  syncPolicy:
    automated:
      prune: true