apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: solidvessel
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: app
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 32101
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 32102