apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: solidvessel
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:4.1.3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        envFrom:
        - secretRef:
            name: rabbitmq-secret