{{ if eq .Values.environment "test" }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: solidvessel
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: cmFiYml0dXM=
  RABBITMQ_DEFAULT_PASS: cmFiYml0dXM=
{{ end }}
---
{{ if eq .Values.environment "prod" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: solidvessel
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgB1lInAoXX79sMsn2MYNa8XlIWpK/ZEX8AgC06oYkHad/u/kMer3pzHNcRt9Bc4PjckujERpykrv5gRNsq2K+0PLLgXiBawCGyh3VN8HmFosi/5xc++/BXR6DSC6kPOQa7d/rnRHfulIm/ZglA9Jbet8fq6atuZKU9veeRMI4vYU/P7JmlHDHEx4PtyXEcArAXCkfNKGlInCQDr3yDK9C9zA6cQYJKY7w0tPpRCsRo/khJ3BIYRP75D3THm1GyplngIkeo6khWcCuBIlpx7R3ln1COhmgyJpO0Fk5SkA0KC3rF1imOnFIZgk3wKy0n027Vid1+Wb/ytDYMfyxQiSIO6Y71P5Ihui8Zd8JcbJEv9seiLs9RCX8HHkl8wvT0FIRLnCA44tJmaKbFCG284RwDk/PSYONjmu8rJVYg0qqP9/YJYgYTXEEdjKoQ/CUr1PsX+GkHuGdfFXt+xrY9NiFRMLM2fyZIyp7e87PI34zqVp//6cKPbdx9K/kH2AkMJ6eHB4+PVPNzogWFZqtylRJudVcKzOUI4B1jw+jkakf5DscqdnZB4Uf4iwQ8yIG9W5hG350BDLpCjJOKo0PERCk/7F3GM9QYvRRgS5wUBNIaaYcj2kUhm6nIAPnx9A9PZo6Jm811P26i/wlzSe4r6l4BFpxqEm93Dkmz5YoaSGQ9rVZFtfmpp808L1wUIyJfaYEYoajD+Pyl/ag==
    RABBITMQ_DEFAULT_USER: AgBQ1AZLMg+Lf4QZOLPybcZY7oLGr4DfyEfoOr4kn8ErJHuFHiy2qsTJBULnvEASGpWyUFfL8EjE1MsaDn55MaKb9G/Wxnl/yvTRuMhyujqlp3Xe81BnxcApLZYjOdQ7FFk/Xdyat1BLYe/pLhaXQOM1Je7tBdcn7VD5XTF/GR8Y757ztTLIaIg1SSLdtBHHTMA7ql486LfWtOj0MviKM6O1xcztDYhoZhUCgGg57o31+VEAsIbXvpWEvjaEXtgj397P8NYr6LLNysVPcCn2soO5xm7U9EePtN3LcBfyp7WZX7dQycEh/L9Xcl5/QHkomUAp1VuQF3iZg6NJPgVK16rYB1Qq7JiZmtNiv/xKyqxQi18hQxEq5glolaf+pmb0J7uBzVVm2mcjpAJGb5ejA3uqYWFNXKdlTlyLfnYvBNw7VM9NspNej/n97zlivwz5iGQ3txqZl4DJrLHm14mik1aeLEioSdBk53xLpX8dAlpufqERryyU9+poZ7HL/GrwcbS4toO74iwiiRQpXkLBq56/d1Kj+buAF8qpeJI9V0gZ4hMdqioMtvkvZJqq9GmVR4tAUNLv9+QBCfEf1U/d1yTlnCaqm0UPWuedCcObKf9RQVf7I4Y4HEDJrBUHrcAzwXKxlAoXuKR7VvJxrqOSIKVRq1G+XCXkEF2MOArXSYi2IbaIvXHgJCuNTjQdXR0vZZF7bLwgdVk/JQ==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: solidvessel
    type: Opaque
{{ end }}