{{ if eq .Values.environment "test" }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: solidvessel
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: cmFiYml0dXM=
  RABBITMQ_DEFAULT_PASS: cmFiYml0dXM=
{{ end }}
---
{{ if eq .Values.environment "prod" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: solidvessel
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgCR9d2sr8jH5a8edeIdGh0HrUQ3dEGhPGkWb+zu3Tbwb2UPsnBhyMLf1He/6kh8tIscYe/myZB/uGI1zB1v2Xmvt2uHVYB9Z7lceJSvvmdjXlbrPxuU1eLaV0h4DlBqzYPTAm1Xn7tdh6fUM43X7LxhkvnQfZTECjU8AVcnBMb1XNA01OtGq4geBvZyw0+46Hj97EMuDx83UdjwxNtH/F1IS4A9OEHCIz5hBiG9ZUbZxmvtoJB8Hp1hHWN7v1O3RKr18IrL+0ivachJ0YllMe68cqWnhANlj6whQ2ZEtKNPgVQ7HRhv3o776FfIbrtcTr8UzLsmLejlp5XBOTXdj2M3bQmevFU+R1JYTtDr8JvGJVCIYFQpqY3XmhSSsWNar0gXo1/Dtnz9yPqAbhesE5WcGBwVBWwXhbLw0s3TM1ZKLhoPzjcyV3e317PZDUFTPbbh1Mo1h0IU+tNfMV8zejdnD9QPoQo3KedqzlyFCmVoEbmijYZjaC/i+vWrCJaU4aKzzDs45tE2oZ3fpZDUu45O84yoTNPp/auPwKIEinMPcdpEJbj06lvkCxaqSQPNTMXJQNYp/DrfMjWmaKwvvRWn3V92cKIeKJ3apzPvE6ZicBZN/IwyXeKN4zCXDwxi5e7dEGbtMQhv91qk/2B6E2dY1M3HXStorxsmZEpCunPob3FcMqX+JMRmAHFbzTT1mII330FDb3G8Zw==
    RABBITMQ_DEFAULT_USER: AgCG/bsXrFKRyDjDTn78ySBiXptraJIgbFaNq+cg3xNRxTjPFQBjpF/OGGempI/8NqaH+NqVA//pT7gxXFOY6pMifSP5hNhWrooQscSnQugdqM92MxD01K5cZ20rJnuqd3RyGYKxWAt9rKirEPTtSJ52HTsCMRXlvHzRnhj3glb3a9xkF7+T7sZGTH8ypSsErVoA6wXQ9OCj3K+c0GYRjnn9oYPMxw4/qfxgXO6uRCf7Xbzf4BfG0tCT7H/JdBv36lcqZrPwjx2s4WfDLZ3icepLevm2O0KoZ+5lryh2SWX/W3Pe0LennInkIDDeJGfu0DGhxKWo7l1auwqRzoyRCGKlDdqUbmKs0eg2GbLCDUrJxZlspCGGgIuXmkWrdBfsVEY/8sUefEP4a4JVwatNSNqLQBgmgJR65tA32y87hNEta+9O+Ao/wZDkE9vD2mfkEIhOtOR3q2EXJ3p3sbIcuPDnVXkr2+qGiNoVkzhrZoW24z99Qr/jSWYVOynYZaLNG+pJ4OhyHZQ+Dn98KyI3UmY5JBXyu+c9p3Ek9ZL16/EyEUKM25QOue4DVPgsiAXjSu+6ilEHUWwkC9uBZr1ebXJ2j7Y0oGZURtaMhAxzlQEuHd/QkCRrTrS+llDkrGQ95B1rM9ZtMr4GARQAftamDT+HJzTzPmdsneo1Z9Nks8YCMzpK97slC7m4CVYiYDvd0aP+Mf4+ZwlzBw==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: solidvessel
    type: Opaque
{{ end }}