{{ if eq .Values.environment "test" }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: solidvessel
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: cmFiYml0dXM=
  RABBITMQ_DEFAULT_PASS: cmFiYml0dXM=
{{ end }}
---
{{ if eq .Values.environment "prod" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: solidvessel
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgCFL4cF3DmFVyperaTxziSdSaiEtc1TFDrUDRxA29wqPwQMoFQE8fg3aCudljx9kcEd/w0BZ+bHymiR9NNvNaU7TU8u0s5FlCXyHiLetxqjSjIyd/bKuVKv2pbwUgjwKjA/W6c4DNlj8JLZJVbi6bZ69ajH5RaQuFyD1gjHXG/gHs/UOvItfklcVkZKQMgmGbf+TN/Ym7y+glCB6SS8JPhN7bLkvnnKaPzz86ML3jZ47UsxF+M6JB4wk0w8sgEjdH0d7Edef5nN0sdG1uAAEvnMiNp9iM7FOqUrMNs6svefIYslsjcFu26nD7wT5P3THVc3K/5pyty0JN/2MYnSdVVkWkKOxiuMXVITJ7vyjEdak67krJdctCYPa3vvD5JN1V1c05LuRJym5MTGNJeLAG5YNDWuzVmgVFMo6fw9RNu10HT7vgMQUk7NJMgxCJMYfsTrHq+IJA+aeXUM7EE66/8Re2FG05EMBvd6uGCUmF+/0m67LwsoMTDP47pwJrsPrfFcjN7QZsACPtJ9Ex8gfa32lhDsk+yQXVxgbbz+CA+LnIhjPsugPQ0TvUTYB4lOU3sbbjRexJ3yPwzLZ6BLlu80S6ng0b7e5RAgKQfAkcsmATNEKcjGczf+KCZZfm+gLfvLKcGzisOU3ekFVLbiaLSJ0D0wZUvPVaCdn3/1PiL55i0HtTOzBChYzUzG8ijYIgoB221BlaHj2g==
    RABBITMQ_DEFAULT_USER: AgAu4FO04tWBy+W/OQdeq1+rpHc4dbHOUafvOhX51jcixxoXCfRxR16dmrvHErhivmPfmvQ/jtO83t7GRgUrqg1mwGol4d1dc9IJFW+A4IVlYPn5h13LbRVKfc7pQyxA+bKfymd5W5RemOKf3ThAUkPXTkPgEKV82OdhImSeR6uF+luAWLR6hIRT9TNpnW/RRupsLKprIaMCrLg//ovcE0eugjVO9rra2pvDc14UL36xirzNh8XKjIsM7dybkCuENnmw7JVvg0WGmjakTLWL4mhsb2KaKQ8zEW/BFNgNrM0RhsJhL1urnGIWj4vm7g/mBMbCVX5vpD4F5lMETIJ5Bj4RWzS4FVuVYZBEMG9OhNfFss8W91KJK5EP0TiIKASBMgnBWSTvLe8cgxSmwqAy3JRKYLqUC1dJ9mugSq2usEh+WMJojn5kklPIMWECwvwRH9vcGQz/tmO7y90m/+SeHPtH1f5jY+gwI0Efxtfy29qm+D7PCGniFtG8g9vKDlI0RxC9jEJbJTWsSJPla9DL9qvrj4jK6WfJT8iBKtISjKi08bk04df48q65cXwds2RuVWADVUkvk2Q/2IoJbA6CKKaKfORj16ldzbR3F/E718BcdXcg+SDMB+XFqg7BuDLdOqXFR9Q74jnCg8k9qeCCMr2hKJuNRi8lxsmShNsX2vy/hVidOpn0Jwmsm5fh5GU5oXqydVAhVA3I2w==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: solidvessel
    type: Opaque
{{ end }}