spring:
  profiles:
    active: dev
  application:
    name: account
  datasource:
    username: nihilus
    password: nihilus
  session:
    store-type: redis
  data:
    redis:
      timeout: 30000
  liquibase:
    change-log: classpath:/db/master.yaml
server:
  servlet:
    context-path: /account
exchanges:
  signUp: signup.topic
queues:
  customer: customer.queue
routing-keys:
  user:
    saved: user.saved