server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9876/realms/solidvessel/protocol/openid-connect/certs
order:
  url: http://localhost:8083/order
payment:
  url: http://localhost:8084/payment
management:
  endpoints:
    web:
      exposure:
        include: '*'
keycloak:
  server-url: http://localhost:9876