spring:
  profiles:
    active: dev
  application:
    name: account
  data:
    redis:
      timeout: 30000
  liquibase:
    change-log: classpath:/db/master.yaml
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
server:
  servlet:
    context-path: /account
keycloak:
  realm: solidvessel
  client-id: solidvessel-auth
  username: solidvessel-admin
