spring:
  datasource:
    url: jdbc:postgresql://account-db-postgresql:5432/account
  data:
    redis:
      host: redis-master
      port: 6379
order:
  url: http://order:8080/order
payment:
  url: http://payment:8080/payment
management:
  endpoints:
    web:
      exposure:
        include: *