apiVersion: v1
kind: ConfigMap
metadata:
  name: account
  namespace: solidvessel
data:
  application-test.yaml: |
    spring:
      datasource:
        url: jdbc:postgresql://account-db:5432/account
        username: nihilus
        password: nihilus
      data:
        redis:
          host: redis-master
          port: 6379
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: http://keycloak:8080/realms/solidvessel/protocol/openid-connect/certs
    order:
      url: http://order:8080/order
    payment:
      url: http://payment:8080/payment
    management:
      endpoints:
        web:
          exposure:
            include: '*'
    keycloak:
      server-url: http://keycloak:8080
