apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  namespace: solidvessel
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: [ 'sh', '-c', "until nslookup account-db.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for database; sleep 1; done" ]
      - name: wait-for-keycloak
        image: busybox
        command: [ 'sh', '-c', "until nslookup keycloak.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for keycloak; sleep 1; done" ]
      containers:
      - name: account-app
        image: ahmsay/solidvessel-account
        imagePullPolicy: Always
        args: [ "--spring.profiles.active=test" ]
        ports:
        - containerPort: 8080