apiVersion: v1
kind: Service
metadata:
  name: account
  namespace: solidvessel
spec:
  type: NodePort
  selector:
    app: account
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31001