apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: solidvessel
  labels:
    app: order-db
spec:
  selector:
    app: order-db
  ports:
  - name: order-db
    port: 5432
    targetPort: 5432
    nodePort: 32003
  type: NodePort