spring:
  profiles:
    active: dev
  application:
    name: order
  datasource:
    username: nihilus
    password: nihilus
  session:
    store-type: redis
  data:
    redis:
      timeout: 30000
  liquibase:
    change-log: classpath:/db/master.yaml
server:
  servlet:
    context-path: /order
exchanges:
  payment: payment.topic
queues:
  order: order.queue
routing-keys:
  payment:
    saved: payment.saved