spring:
  profiles:
    active: dev
  application:
    name: order
  data:
    redis:
      timeout: 30000
  liquibase:
    change-log: classpath:/db/master.yaml
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
server:
  servlet:
    context-path: /order
exchanges:
  payment: payment.topic
queues:
  payment:
    approved: payment.approved
routing-keys:
  payment:
    approved: payment.approved
keycloak:
  realm: solidvessel
  client-id: solidvessel-auth
  username: solidvessel-admin
