spring:
  datasource:
    url: jdbc:postgresql://order-db:5432/order_db
    username: nihilus
    password: nihilus
  data:
    redis:
      host: redis-master
      port: 6379
  rabbitmq:
    host: rabbitmq
    port: 5672
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/solidvessel/protocol/openid-connect/certs
payment:
  url: http://payment:8080/payment
management:
  endpoints:
    web:
      exposure:
        include: '*'
keycloak:
  server-url: http://keycloak:8080
