spring:
  datasource:
    url: jdbc:postgresql://order-db-postgresql:5432/order_db
  data:
    redis:
      host: redis-master
      port: 6379
      password: nihilus
  rabbitmq:
    host: rabbitmq
    port: 5672
    password: nihilus
payment:
  url: http://payment:8080/payment
management:
  endpoints:
    web:
      exposure:
        include: *