spring:
  datasource:
    url: jdbc:postgresql://orderdb.solidvessel.com:5432/order_db
  data:
    redis:
      host: redis-master
      port: 6379
      password: nihilus
  rabbitmq:
    host: rabbitmq
    port: 5672
    password: nihilus
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:80/realms/solidvessel/protocol/openid-connect/certs
payment:
  url: http://payment:8080/payment
management:
  endpoints:
    web:
      exposure:
        include: '*'
keycloak:
  server-url: http://keycloak:80
