spring:
  profiles:
    active: dev
  application:
    name: order
  datasource:
    username: nihilus
    password: nihilus
  data:
    redis:
      timeout: 30000
  liquibase:
    change-log: classpath:/db/master.yaml
    contexts: sql,data
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
server:
  servlet:
    context-path: /order
exchanges:
  payment: payment.topic
queues:
  payment:
    approved: payment.approved
routing-keys:
  payment:
    approved: payment.approved
keycloak:
  realm: solidvessel
  client-id: solidvessel-auth
  client-secret: GJDCy4C7LSeFmggaRtZutSHZHBaTCavE
  username: solidvessel-admin
  password: svadmin