apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solidvessel-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ahmsay/Solidvessel.git
    targetRevision: master
    path: .kubernetes/mainapps
    helm:
      valueFiles:
      - values-test.yaml # this line will be changed to values-prod.yaml automatically during a production build
  destination:
    server: https://kubernetes.default.svc
    namespace: solidvessel
  syncPolicy:
    automated:
      prune: true