apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solidvessel-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ahmsay/Solidvessel.git
    targetRevision: master
    path: .kubernetes/argocd/mainapps
  destination:
    server: https://kubernetes.default.svc
    namespace: solidvessel
  syncPolicy:
    automated:
      prune: true