apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: 22.1.1
    helm:
      values: |
        production: true
        proxy: edge
        auth:
          adminUser: admin
          existingSecret: keycloak-admin-secret
        postgresql:
          enabled: false
        externalDatabase:
          host: keycloak.db.solidvessel.com
          database: keycloak
          user: nihilus
          existingSecret: keycloak-db-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: solidvessel
  syncPolicy:
    automated:
      prune: true
