apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: 17.3.6
    helm:
      values: |
        production: true
        proxy: edge
        auth:
          adminUser: admin
          existingSecret: keycloak-secret
        postgresql:
          enabled: false
        externalDatabase:
          host: keycloak.db.solidvessel.com
          database: keycloak
          user: nihilus
          existingSecretPasswordKey: keycloak-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: solidvessel
  syncPolicy:
    automated:
      prune: true
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-secret
  namespace: solidvessel
spec:
  encryptedData:
    adminPassword: AgCZVUNVwSB58bMb+z6EAjwbZSqNDbdu53vCi4GkSo7d2w1su1oysYy0aloet3ZrI4Lvpm7diqj5AYq7AShBEnj0xn/1gYKtSBnwlIOCloroQRdf8YDtgI2gGNHowzPf2aLDHwFjqqMZ4SaHJSd8utZn62y/0XtQPKjuE1DZVopWunE/9iKD7+eZOh0rfgqStlkSPEXIWu6wfeyLf+SBRgL/sRd5Z26LcQr+ST1VTDEOnDnJO6gxaFD4Xhe6zQWaWPux26akr8qx5URM51ypmRbpS4txUaGhrxr0LM1NgcSe3jGQbOUjGzfnNgFHvtc2S5oDecJ03hh1+/92sHPFiOosigA+THW0j3V+Tg0Z81cu38j/2W8O9xOQtPy08usgdDpIbm0xPNmH1dBut6lVV2BwQevU6bV5tKeCSmKPs/LKCsMz39/flcEAj0PxAF2bEDadoXCjvLEJZC1uOon5TrabTTnlsgRUtNW7GWSPBHO/fjIwKJ1Ow/K4RDRT8swDLxzB4AGu0zGdTxVqJhkNX0IbXQMIQGInVjyibI0edwWGwAYEaOB9MgBmSPLJ0kz6/ein+MN9b3+DIJTD6xxlppUdhn+pasTNJK5ODO3Zh1oftd9AF3LYloMjCx0jJe/eQg466xRyDpvVxE8uIoNOs04yKW0nl0uHOovAIMj6rUMZjzwseEVBNJR9aGjpnbjTOu0OB6JWEHHh+PYNGm97qnKZlkDKtg==
    postgresPassword: AgAeyKwwPN4v5rm6CGOrRJfsjZ3kWDexeHfdaOC+0Yj5N/gxZcbmWd86NimfMZTgG8FNZijDhhzysq0iKhXgFdOXL62yNkovKMpkNsJb99+dnyn1CyweQ3+SC7tWCIF4F1pfasmvB8A0yaflEAGRTJw054fLDbE38F45Tx5y4bMSf4iZCBz1KUThB1Z7nSrNS/wVoTvK1nZZzwo9ic61jiiugSRnBcyzLFnziDkdvAAVoHMoRAi3IMBU+RRkMQO+o0xcWTXb9Og/LVzqdtXMhsfajTV5FiIBuNEYydpmjqWgxgdD41MXEWni22W5ffnshDY8L2bZeBLya0L4ZT1S5/1Ih8OCGolTKgPucUBqmvdfzG83CMHkeG+h0C6+KMCaaHx1UAxMNj5qVVrqRk94DT2rCESbFk+5SxZwvwrtVXx8ytS3/RgTt+6Mmn0MrLSn2uYgH9gPm3+hXOAFrip5CRq+Zo0KYpkHqOdYU6n6nYcVYm8zNec+uKTJdE1vDBwXQv+GMxZLWc+0KbUoUW+1RXnuX5xkdRchAs+9iLc9yG0dKYIV3Tw61jKfJhTY9KVI0Terw7+Lp5or5eMpR0VcIAwS3+jYT5wSa/f6ualgWYXP3RBFIxX+EFmADnr9aVvD8G0KrF9TExtGZb/Pca8gxHkjwGw0EHMAjw8fmAoTOFUtgT0c4lUTNBXbiro0wUa7VZSPzwnVvf/iZPYi6LBC8iTAr2pWQw==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-secret
      namespace: solidvessel
    type: Opaque