apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: 17.3.6
    helm:
      values: |
        production: true
        proxy: edge
        auth:
          adminUser: admin
          existingSecret: keycloak-secret
        postgresql:
          enabled: false
        externalDatabase:
          host: keycloak.db.solidvessel.com
          database: keycloak
          user: nihilus
          existingSecretPasswordKey: keycloak-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: solidvessel
  syncPolicy:
    automated:
      prune: true
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-secret
  namespace: solidvessel
spec:
  encryptedData:
    admin-password: AgCZVUNVwSB58bMb+z6EAjwbZSqNDbdu53vCi4GkSo7d2w1su1oysYy0aloet3ZrI4Lvpm7diqj5AYq7AShBEnj0xn/1gYKtSBnwlIOCloroQRdf8YDtgI2gGNHowzPf2aLDHwFjqqMZ4SaHJSd8utZn62y/0XtQPKjuE1DZVopWunE/9iKD7+eZOh0rfgqStlkSPEXIWu6wfeyLf+SBRgL/sRd5Z26LcQr+ST1VTDEOnDnJO6gxaFD4Xhe6zQWaWPux26akr8qx5URM51ypmRbpS4txUaGhrxr0LM1NgcSe3jGQbOUjGzfnNgFHvtc2S5oDecJ03hh1+/92sHPFiOosigA+THW0j3V+Tg0Z81cu38j/2W8O9xOQtPy08usgdDpIbm0xPNmH1dBut6lVV2BwQevU6bV5tKeCSmKPs/LKCsMz39/flcEAj0PxAF2bEDadoXCjvLEJZC1uOon5TrabTTnlsgRUtNW7GWSPBHO/fjIwKJ1Ow/K4RDRT8swDLxzB4AGu0zGdTxVqJhkNX0IbXQMIQGInVjyibI0edwWGwAYEaOB9MgBmSPLJ0kz6/ein+MN9b3+DIJTD6xxlppUdhn+pasTNJK5ODO3Zh1oftd9AF3LYloMjCx0jJe/eQg466xRyDpvVxE8uIoNOs04yKW0nl0uHOovAIMj6rUMZjzwseEVBNJR9aGjpnbjTOu0OB6JWEHHh+PYNGm97qnKZlkDKtg==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-secret
      namespace: solidvessel
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-externaldb
  namespace: solidvessel
spec:
  encryptedData:
    db-password: AgBOBXKf79qMzL5lhnpnMUlaZUKAd69vIahH+lvnwqmOSaTPB8YKHW2MXz2TYVsDbOp54wDufqm1z5JiJcZr3tm+26lldCOkCIVXfnGcBaydDwhKH0ydE1xWNX2BZ+WdfIzN2RcV7Uz17ayqTdH5B0gAQGwkSP6ci08TCxTL3rM3uSOCP2tGumGl7kbowHH4BVX9MUzplVWQTOK9FZmJgkWFvdQFOSY29/l+7FpaCPqIzgYXkg+4gmvuWe0X/JIKmNDq0l++mpUAhwsC0vZBU2LXd3s4GNxG5s5+deTXIA0/7wtXkZbNgHRFMbPVUK/npqzOGtnoQq9dsafno/MuneDhMe4HaWMZwjsvdSRvP1fGsqfDukePYwnFSQ3/lMybG7SF2RmpN8nxroyQUR69X8RXIVlEjATSG6/RlZgD2ihLuRGA+Pfspvcg3AF3J++e37roG84J6IxuKxjqmijod2IAwb1GFSuXZLPjvQJZvBI/SrBPjJsr2KT2R+2Qr9i1x5MOVHwR3y/nOJwmHEgfZAdzWUtWegVdMyLGBISOpdKEFVrfE9fkH4ZqcI9z2T2VSR2XyddjBY/Ek7TnQXdX21Is8XetPImByzsswKlweb0cylQ7IbS8eC2Xix9N63X3EqE4wXuDJbE52e1RGdkcjhd1OElQXkIYCkAsjWV5DLlfLlwVqTZbkKBE0UZdup4nYn2v+QnXB+xFe/hIu8TjZ3kFAaoRrA==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-externaldb
      namespace: solidvessel
    type: Opaque
