apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 18.4.0
    helm:
      values: |
        auth:
          existingSecret: redis-secret
        master:
          persistence:
            enabled: false
        replica:
          persistence:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: solidvessel
  syncPolicy:
    automated:
      prune: true