apiVersion: v1
kind: Service
metadata:
  name: inventory-db
  namespace: solidvessel
spec:
  type: NodePort
  selector:
    app: inventory-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32002