version: "3"
services:
  postgres:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=nihilus
      - POSTGRES_PASSWORD=nihilus
    ports:
      - "5432:5432"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7.2-rc2
    ports:
    - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.12.0-management
    ports:
    - "5672:5672"
    - "15672:15672"
  apisix:
    container_name: apache-apisix
    image: apache/apisix
    environment:
      APISIX_STAND_ALONE: "true"
    volumes:
    - ./apisix-conf.yaml:/usr/local/apisix/conf/apisix.yaml
    network_mode: host