spring:
  datasource:
    url: jdbc:postgresql://payment.db.solidvessel.com:5432/payment
    username: nihilus
    password: 5b03574a-fe81-2d65-553a-68e6a3485ea7
  data:
    redis:
      host: redis-master
      port: 6379
      password: nihilus
  rabbitmq:
    host: rabbitmq
    port: 5672
    password: nihilus
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:80/realms/solidvessel/protocol/openid-connect/certs
management:
  endpoints:
    web:
      exposure:
        include: '*'
keycloak:
  server-url: http://keycloak:80
