spring:
  profiles:
    active: dev
  application:
    name: payment
  datasource:
    username: nihilus
    password: nihilus
  data:
    redis:
      timeout: 30000
  liquibase:
    change-log: classpath:/db/master.yaml
    contexts: sql,data
server:
  servlet:
    context-path: /payment
exchanges:
  payment: payment.topic
routing-keys:
  payment:
    saved: payment.saved
keycloak:
  realm: solidvessel
  client-id: solidvessel-auth
  client-secret: GJDCy4C7LSeFmggaRtZutSHZHBaTCavE
  username: solidvessel-admin
  password: svadmin