apiVersion: v1
kind: Service
metadata:
  name: payment-db
  namespace: solidvessel
spec:
  type: NodePort
  selector:
    db: payment
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32004