plugins {
    id 'java-library'
    id 'io.freefair.lombok'
    id 'jacoco'
}

base {
    archivesName = 'payment-domain'
}

dependencies {
    api project(':shared:domain')
    testImplementation libs.junit.api
    testRuntimeOnly libs.junit.engine
    testRuntimeOnly libs.junit.platform.launcher
    testImplementation libs.mockito
    testImplementation libs.mockito.junit
}
