apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: solidvessel
spec:
  template:
    spec:
      containers:
      - name: inventory-app
        args: [ "--spring.profiles.active=prod" ]
