version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
    - wget https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.1%2B12/OpenJDK21U-jdk_x64_linux_hotspot_21.0.1_12.tar.gz
    - tar -xvf OpenJDK21U-jdk_x64_linux_hotspot_21.0.1_12.tar.gz
    - sudo mv jdk-21.0.1+12 /opt/
    - export JAVA_HOME=/opt/jdk-21.0.1+12
    - export PATH=$PATH:$JAVA_HOME/bin
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
  pre_build:
    commands:
    - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s9i7g5t1
  build:
    commands:
    - gradle test --parallel
    - ./codecov
  post_build:
    commands:
    - gradle jib
reports:
  test-results:
    files:
    - '**/*Test.xml'
