version: 0.2
env:
  shell: bash
phases:
  pre_build:
    commands:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
  build:
    commands:
    - gradle test --parallel
    - ./codecov
    - gradle jib -Pjib.to.auth.username=$DOCKER_USERNAME -Pjib.to.auth.password=$DOCKER_PASSWORD
reports:
  test-results:
    files:
    - '**/*Test.xml'
