version: 0.2
env:
  shell: bash
phases:
  pre_build:
    commands:
    - wget https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.1%2B12/OpenJDK21U-jdk_x64_linux_hotspot_21.0.1_12.tar.gz
    - tar -xvf OpenJDK21U-jdk_x64_linux_hotspot_21.0.1_12.tar.gz
    - sudo mv jdk-21.0.1+12 /opt/
    - export JAVA_HOME=/opt/jdk-21.0.1+12
    - export PATH=$PATH:$JAVA_HOME/bin
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
  build:
    commands:
    - gradle test --parallel
    - ./codecov
    - gradle jib -Pjib.to.auth.username=$DOCKER_USERNAME -Pjib.to.auth.password=$DOCKER_PASSWORD --parallel
reports:
  test-results:
    files:
    - '**/test/index.html'
