apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: solidvessel
  labels:
    app: inventory
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: [ 'sh', '-c', "until nslookup inventory-db-postgresql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for database; sleep 1; done" ]
      - name: wait-for-keycloak
        image: busybox
        command: [ 'sh', '-c', "until nslookup keycloak.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for keycloak; sleep 1; done" ]
      containers:
      - name: inventory-app
        image: ahmsay/solidvessel-inventory
        imagePullPolicy: Always
        args: [ "--spring.profiles.active=test" ]
        ports:
        - containerPort: 8080
