environment: test
image:
  tag: "1.0.0"
db:
  hostname: account-db.solidvessel.svc.cluster.local
  url: jdbc:postgresql://account-db:5432/account
spring:
  webExposure: "*"
  liquibase:
    contexts: sql,data
replicas: 1
