environment: test
db:
  hostname: account-db-postgresql.solidvessel.svc.cluster.local
  url: jdbc:postgresql://account-db-postgresql:5432/account
spring:
  webExposure: "*"
  liquibase:
    contexts: sql,data
replicas: 1