environment: test
image:
  repository: public.ecr.aws/s9i7g5t1/solidvessel/account
  tag: "0.1.0"
  pullPolicy: IfNotPresent
db:
  hostname: account-db.solidvessel.svc.cluster.local
  url: jdbc:postgresql://account-db:5432/account
spring:
  webExposure: "*"
  liquibase:
    contexts: sql,data
replicas: 1
