apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: solidvessel
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - name: app
      protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 32103