apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: solidvessel
  labels:
    app: inventory
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: [ 'sh', '-c', "until nslookup {{ .Values.db.hostname }}; do echo waiting for database; sleep 1; done" ]
      - name: wait-for-keycloak
        image: busybox
        command: [ 'sh', '-c', "until nslookup keycloak.solidvessel.svc.cluster.local; do echo waiting for keycloak; sleep 1; done" ]
      containers:
      - name: inventory-app
        image: ahmsay/solidvessel-inventory
        imagePullPolicy: Always
        args:
        - "--spring.profiles.active={{ .Values.environment }}"
        - "--spring.datasource.url={{ .Values.db.url }}"
        - "--spring.datasource.username=nihilus"
        - "--spring.datasource.password={{ .Values.db.password }}"
        - "--spring.data.redis.host=redis-master"
        - "--spring.data.redis.port=6379"
        - "--spring.data.redis.password={{ .Values.redis.password }}"
        - "--spring.rabbitmq.host=rabbitmq"
        - "--spring.rabbitmq.port=5672"
        - "--spring.rabbitmq.password={{ .Values.rabbitmq.password }}"
        - "--spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/solidvessel/protocol/openid-connect/certs"
        - "--management.endpoints.web.exposure.include={{ .Values.spring.webExposure }}"
        - "--keycloak.server-url=http://keycloak:8080"
        - "--keycloak.client-secret={{ .Values.keycloak.clientSecret }}"
        - "--keycloak.password={{ .Values.keycloak.password }}"
        ports:
        - containerPort: 8080
        {{ if .Values.environment "prod" }}
        envFrom:
        - secretRef:
            name: inventory-secret
        {{ end }}