plugins {
    id 'java'
    id 'io.freefair.lombok'
}

base {
    archivesName = 'shared-domain'
}

dependencies {
    implementation libs.junit.api
    runtimeOnly libs.junit.engine
    testRuntimeOnly libs.junit.platform.launcher
    implementation libs.mockito
    implementation libs.mockito.junit
}
