apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: solidvessel
spec:
  type: NodePort
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31003