apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: solidvessel
  labels:
    app: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: [ 'sh', '-c', "until nslookup order-db.solidvessel.svc.cluster.local; do echo waiting for database; sleep 1; done" ]
      - name: wait-for-keycloak
        image: busybox
        command: [ 'sh', '-c', "until nslookup keycloak.solidvessel.svc.cluster.local; do echo waiting for keycloak; sleep 1; done" ]
      containers:
      - name: order-app
        image: ahmsay/solidvessel-order
        imagePullPolicy: Always
        args: [ "--spring.profiles.active=test" ]
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              key: JAVA_OPTS
              name: order-configmap-test