spring:
  profiles:
    active: dev
  application:
    name: auth
  datasource:
    username: nihilus
    password: nihilus
  session:
    store-type: redis
  data:
    redis:
      timeout: 30000
  liquibase:
    change-log: classpath:/db/master.yaml
server:
  servlet:
    context-path: /auth
exchanges:
  signUp: signup.topic
routing-keys:
  user:
    saved: user.saved