spring:
  datasource:
    url: jdbc:postgresql://auth-db-postgresql:5432/auth
  data:
    redis:
      host: redis-master
      port: 6379
      password: nihilus
  rabbitmq:
    host: rabbitmq
    port: 5672
    password: nihilus
management:
  endpoints:
    web:
      exposure:
        include: *